### ISSUE TITLE
Replace class 'FingerprintThread' with method 'def on_fingerprint' in Kiosk.py

### ISSUE THREAD

**Issue by WK-GiHu** [Justinjay282/qwerty#31]
@Justinjay282 

- [ ] `def on_fingerprint(...`

  **Note**: `result` becomes `FingerprintThread.template`
  and
  `FingerprintThread.result` becomes `event.result`

**Comment by Justinjay282** [comment]
sir @WK-GiHu, I've committed a changes in `Main_Kiosk.py` I'm kinda confused in 
```
class Event: pass
```
can you review what I did.

**Comment by WK-GiHu** [comment]
@Justinjay282 

>confused in `class Event: pass`

Ok, forget this, we can use the event from `def on_fingerprint(self, event)`

Read again https://github.com/Justinjay282/qwerty/issues/31#issue-580488905

**Comment by Justinjay282** [comment]
sir @WK-GiHu, I've edited the `Kiosk_Main.py` 

https://github.com/Justinjay282/qwerty/blob/b4bf9602915cc3f9ff5d1663a1e38607c507c693/Kiosk_Main.py#L193
https://github.com/Justinjay282/qwerty/blob/b4bf9602915cc3f9ff5d1663a1e38607c507c693/Kiosk_Main.py#L194

**Comment by WK-GiHu** [comment]
@Justinjay282 

Still not what it should be
https://github.com/Justinjay282/qwerty/blob/b4bf9602915cc3f9ff5d1663a1e38607c507c693/Kiosk_Main.py#L193

No progress, here
https://github.com/Justinjay282/qwerty/blob/b4bf9602915cc3f9ff5d1663a1e38607c507c693/Kiosk_Main.py#L204

Read again https://github.com/Justinjay282/qwerty/issues/31#issue-580488905

**Comment by Justinjay282** [comment]
sir @WK-GiHu, I added method def on_fingerprint(self, event): like in FingerprintDevice.__main__

I tried it and now running withour error.

the output is
```
on_grant_access()  positionNumber=4,  accuracyScore=130
```
depends on the value of a template

**Comment by WK-GiHu** [comment]
@Justinjay282 

>I tried it and now running withour error.

OK, but you have removed the copy of the code block from
https://github.com/Justinjay282/qwerty/blob/8913cb0429b860b6dcd56144a23c5020bba23585/Kiosk_Main.py#L59-L74

### Revert it an obey https://github.com/Justinjay282/qwerty/issues/31#issue-580488905

**Comment by Justinjay282** [comment]
> @Justinjay282
> 
> > I tried it and now running withour error.
> 
> OK, but you have removed the copy of the code block from
> https://github.com/Justinjay282/qwerty/blob/8913cb0429b860b6dcd56144a23c5020bba23585/Kiosk_Main.py#L59-L74
> 

I added the code block above, I think it's now working again on login. Also, I changed the `FingerprintThread.result` to `event.result`

> ### Revert it an obey [#31 (comment)](https://github.com/Justinjay282/qwerty/issues/31#issue-580488905)
> I'm offline for on hour.

Okay, sir, Take Care :) I'll take a break for at least 30mins and eat then go back here immediately.

**Comment by WK-GiHu** [comment]
@Justinjay282 

- [ ] For readability, rename all `fingerprint` to `template`
  https://github.com/Justinjay282/qwerty/blob/43832ae88ceef706889ad9912dc604ab79bf7892/Kiosk_Main.py#L205-L210

- [ ] Why twice ?
  https://github.com/Justinjay282/qwerty/blob/43832ae88ceef706889ad9912dc604ab79bf7892/Kiosk_Main.py#L212-L213

- [ ] Replace **both**, as before
  https://github.com/Justinjay282/qwerty/blob/43832ae88ceef706889ad9912dc604ab79bf7892/Kiosk_Main.py#L218
  https://github.com/Justinjay282/qwerty/blob/43832ae88ceef706889ad9912dc604ab79bf7892/Kiosk_Main.py#L224

  with
  ```
            event.state = 1  #  admin or event.state = 2  # residents
            self.on_grant_access(event)
  ```

Test if Login works as before.
Close this Issue if it's working and continue with https://github.com/Justinjay282/qwerty/issues/32

**Comment by Justinjay282** [comment]
> @Justinjay282
> 
> * [x]  For readability, rename all `fingerprint` to `template`
>   https://github.com/Justinjay282/qwerty/blob/43832ae88ceef706889ad9912dc604ab79bf7892/Kiosk_Main.py#L205-L210
> * [ ]  Why twice ?
>   https://github.com/Justinjay282/qwerty/blob/43832ae88ceef706889ad9912dc604ab79bf7892/Kiosk_Main.py#L212-L213

This is just a typo error sir.
> * [ ]  Replace **both**, as before
>   https://github.com/Justinjay282/qwerty/blob/43832ae88ceef706889ad9912dc604ab79bf7892/Kiosk_Main.py#L218
>   
>   https://github.com/Justinjay282/qwerty/blob/43832ae88ceef706889ad9912dc604ab79bf7892/Kiosk_Main.py#L224
>   
>   with
>   ```
>             event.state = 1  #  admin or event.state = 2  # residents
>             self.on_grant_access(event)
>   ```
> 
> Test if Login works as before.
> Close this Issue if it's working and continue with #32

It's working now sir, I'll proceed to #32 
Also changed the `fingerprint` to `template.

**Comment by WK-GiHu** [comment]
@Justinjay282 

Adapt the changes from `FingerprintDevice.py`.

**Comment by Justinjay282** [comment]
sir @WK-GiHu, It's working well by having a `from FingerprintDevice_v2 import FingerprintThread`
should I also add these:
```
    def on_fingerprint(event):
        print('on_fingerprint()  positionNumber={}'.format(event.state))

        if event.state >= 0:
            global template_id
            template_id = event.state
            btn2.configure(text=btn2._text.format(template_id))

    def on_register():  # test MODE REGISTER
        global template_id
        template_id = None
        print('set mode REGISTER')
        fp.set_mode(REGISTER)
        
    def on_delete():  # test delete_template
        if template_id is not None:
            print('delete_template({})'.format(template_id))
            fp.delete_template(template_id)
```
in `class Kiosk`
I'll also fix the template of the fingerprint that have been registered in the fingerprint scanner.

**Comment by WK-GiHu** [comment]
@Justinjay282 

**Review `Kiosk_Main.py`**

- [ ] Remove the whole `class XFingerprintThread`
https://github.com/Justinjay282/qwerty/blob/fc3bae00c7c6b8c543a2ef7fd2404ee208de3d2d/Kiosk_Main.py#L11

- [ ] We need a reference, like in `__main__`
https://github.com/Justinjay282/qwerty/blob/fc3bae00c7c6b8c543a2ef7fd2404ee208de3d2d/Kiosk_Main.py#L193
  ```
  self.fp = Finger....
  ```

- [ ]   This reference have to be used in `class Update_residents.__init__`
  Show where you instantiate `class Update_residents`.

- [ ] Change the top of this function like in `__main__`
https://github.com/Justinjay282/qwerty/blob/fc3bae00c7c6b8c543a2ef7fd2404ee208de3d2d/FingerprintDevice.py#L127-L128
  Add `position_number = event.state`
  I recommend to rename `positionNumber` to `template_id`
  Add a condition if template id == `-1` to prevent sensless `mysql` querys.

**Comment by WK-GiHu** [comment]
@Justinjay282 

### No progress according my last comment https://github.com/Justinjay282/qwerty/issues/31#issuecomment-599140954

We need it to continue with `update_resident_fingerprint.py`

**Comment by Justinjay282** [comment]
sir @WK-GiHu, I updated the `Kiosk_Main.py` `FingerprintDevice.py` and `update_residents_fingerprint.py`
> * [ ]  Change the top of this function like in `__main__`
>   https://github.com/Justinjay282/qwerty/blob/fc3bae00c7c6b8c543a2ef7fd2404ee208de3d2d/FingerprintDevice.py#L127-L128
>   
>   Add `position_number = event.state`
>   I recommend to rename `positionNumber` to `template_id`
>   Add a condition if template id == `-1` to prevent sensless `mysql` querys.

but I can't quite get this one...

**Comment by WK-GiHu** [comment]
@Justinjay282 

>but I can't quite get this one...

Please, rephrase i didn't get your problem?

**Comment by Justinjay282** [comment]
sir @WK-GiHu, I'm confused in "Change the top of this function like in `__main__`
Can you check I edited most of the code, can you check it if I did right?

**Comment by WK-GiHu** [comment]
@Justinjay282 

- [ ] Replace 
https://github.com/Justinjay282/qwerty/blob/4940942647469b06ed56540cbd5875623d41d1a7/Kiosk_Main.py#L139-L144

  with
  https://github.com/Justinjay282/qwerty/blob/4940942647469b06ed56540cbd5875623d41d1a7/update_resident_fingerprint.py#L103-L105

The whole code block line 146 to 161 goes inside the `if ...`
You have to adapt `template_id` accordingly,

**Comment by Justinjay282** [comment]
sir @WK-GiHu, I just edited the code.
so I'll also do like this sir?
move this
https://github.com/Justinjay282/qwerty/blob/7ac00bd640502250386f5e624b7ca0d663a0d864/Kiosk_Main.py#L166-L191
before
https://github.com/Justinjay282/qwerty/blob/7ac00bd640502250386f5e624b7ca0d663a0d864/Kiosk_Main.py#L144
?

**Comment by WK-GiHu** [comment]
@Justinjay282 

- [ ] This part belongs to REGISTER, remove it
  https://github.com/Justinjay282/qwerty/blob/7ac00bd640502250386f5e624b7ca0d663a0d864/Kiosk_Main.py#L144-L147

- [ ] Don't break the previous code block
  https://github.com/Justinjay282/qwerty/blob/7ac00bd640502250386f5e624b7ca0d663a0d864/Kiosk_Main.py#L149

>and the def on_grant_access is for RFID thread alone...

No, no changes there.

**Comment by Justinjay282** [comment]
sir @WK-GiHu, I've edited the code and did this:
https://github.com/Justinjay282/qwerty/blob/0b3e778cc9997c2cb16a959f9fc0a0b1a2632710/Kiosk_Main.py#L138-L157

**Comment by WK-GiHu** [comment]
@Justinjay282 

- [ ] You have broken the previous code block, ident line 142 to 156!
  https://github.com/Justinjay282/qwerty/blob/0b3e778cc9997c2cb16a959f9fc0a0b1a2632710/Kiosk_Main.py#L142

- [ ] You didn't obey the new name `template_id`, there is no more a variabel named `positionNumber`

- [ ] Change **both** to: `return self.on_grant....`
  https://github.com/Justinjay282/qwerty/blob/0b3e778cc9997c2cb16a959f9fc0a0b1a2632710/Kiosk_Main.py#L147
  https://github.com/Justinjay282/qwerty/blob/0b3e778cc9997c2cb16a959f9fc0a0b1a2632710/Kiosk_Main.py#L154

- [ ] Remove the `else` and outident 2 level
  https://github.com/Justinjay282/qwerty/blob/0b3e778cc9997c2cb16a959f9fc0a0b1a2632710/Kiosk_Main.py#L155-L156

### Please don't copy the updated code in comment, i see the whole `Kiosk_Main.py`

**Comment by Justinjay282** [comment]
sir @WK-GiHu, I've edited the code `Kiosk_Main.py`

**Comment by WK-GiHu** [comment]
@Justinjay282 

- [ ] One outident level more, the message have to shown if `event.state == -1` or no match by `mysql SELECT`
https://github.com/Justinjay282/qwerty/blob/e684d8c927ecc1ad1dce66076c411d11419c5ef8/Kiosk_Main.py#L156

**Comment by WK-GiHu** [comment]
@Justinjay282 

Now run all cases:

1. valid scan valid admin
1.1 valid scan invalid admin
2. valid scan valid resident
2.2 valid scan invalid resident
3. Invalid scan

- [ ] Show me where you instantiate `class Update_residents`?

**Comment by Justinjay282** [comment]
sir @WK-GiHu, I tried it, It's working.

I just did the 
import update_admins
import update_residents
and call it
```
    def Update_Residents(self):
        update_residents.Update_residents()
#=============================update module for admin===========================#    
    def Update_Admins(self):
        update_admins.Update_admins()
```

**Comment by WK-GiHu** [comment]
@Justinjay282 

>It's working.

OK, but the indent level of the messagebox is still wrong?

>import update_residents

Didn't see it in `Kiosk_Main.py` ?

**Comment by Justinjay282** [comment]
> @Justinjay282
> 
> > It's working.
> 
> OK, but the indent level of the messagebox is still wrong?

I'm sorry sir, I overextend of one level. 
I added 
```
else:
    messagebox...
```
is it okay?
> 
> > import update_residents
> 
> Didn't see it in `Kiosk_Main.py` ?

I've edited the `Main_Kiosk.py` I didn't include all code since my code is not that good...
But the imports and calling of `update_residents` and `update_admins` are included

**Comment by WK-GiHu** [comment]
@Justinjay282 

>'m sorry sir, I overextend of one level.
>I added
>else:
>    messagebox...

- [ ] The line 159 have  to be on the **same ident level** as `if event.state >= 0:`
 Still, one level to deep.
 https://github.com/Justinjay282/qwerty/blob/868eebd9876f020052b0513ee8501d2ebaed6ae6/Kiosk_Main.py#L159

> the imports and calling of update_residents and update_admins are included

OK, i have overlooked it ...

- [ ] Change to: `update_residents.Update_residents(self)`
https://github.com/Justinjay282/qwerty/blob/868eebd9876f020052b0513ee8501d2ebaed6ae6/Kiosk_Main.py#L224

**Comment by Justinjay282** [comment]
sir @WK-GiHu, I've edited the code, sir.

**Comment by WK-GiHu** [comment]
@Justinjay282 

OK, you claim ***It's working.***, continue with https://github.com/Justinjay282/qwerty/issues/36#
